### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by jenn-jenn** [jenn-jenn/mewTubu#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by jenn-jenn** [comment]
Last of MVP is pending due to integrations with other MVPs

**Comment by carlosaicrag** [comment]
# User Auth

## Functionality

- [ ] The main button with logo should link to `/`
- [ ] Has working demo login
- [ ] Smooth, bug free navigation

### Before Login

- [ ] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [ ] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [ ] Errors should display for both `/signup` and `/login`.
- [ ] Errors should clear when moving between `/signup` and `/login`.
- [ ] Can sign up a user
- [ ] Can sign in as a user
- [ ] Can log out a user
- [ ] Can't sign up with the same username/email
- [ ] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [ ] Should not be able to visit `/login` or `/signup`
- [ ] Should be able to refresh the page and still be logged in


## Style

- [ ] The site should look exactly like the actual site
- [ ] All relevant elements should have `cursor: pointer` on hover
- [ ] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [ ] Remove Redux logger and all console.log()'s from production

## Seeds
- [ ] Adequate and appropriate seeds

**Comment by carlosaicrag** [comment]
<img width="302" alt="Screen Shot 2019-11-12 at 11 57 31 AM" src="https://user-images.githubusercontent.com/30717440/68705891-bb354680-0543-11ea-819f-464c4080fc9c.png">
could use a bit more styling especially on the input boxes.  there should also be a button that takes you back to the home page.

**Comment by carlosaicrag** [comment]
upon clicking the demo login it should sign you in 

also, demo login button should only be on the login page

**Comment by carlosaicrag** [comment]
<img width="304" alt="Screen Shot 2019-11-12 at 12 01 54 PM" src="https://user-images.githubusercontent.com/30717440/68706199-3dbe0600-0544-11ea-9435-37d73ccb84c9.png">
this should be fixed

**Comment by jenn-jenn** [comment]
Most have been fixed

> <img alt="Screen Shot 2019-11-12 at 11 57 31 AM" width="302" src="https://user-images.githubusercontent.com/30717440/68705891-bb354680-0543-11ea-819f-464c4080fc9c.png">
> 
> could use a bit more styling especially on the input boxes. there should also be a button that takes you back to the home page.
> should have a cursor:pointer when hovering over the login button

Styled login/signup page with button effects.

**Comment by jenn-jenn** [comment]
Most have been fixed. Add more styling to the login/signup page

**Comment by jenn-jenn** [comment]
Closing
